services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana_provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
